project:
  name: AstroAssistance
  version: 0.1.0
  description: Self-learning AI productivity assistant

paths:
  data:
    raw: data/raw
    processed: data/processed
    synthetic: data/synthetic
  models: models
  logs: logs

data_processing:
  text:
    max_sequence_length: 512
    tokenizer: bert-base-uncased
  task_data:
    min_samples: 1000
    validation_split: 0.15
    test_split: 0.15

models:
  base_model:
    type: transformer
    embedding_dim: 768
    num_heads: 12
    num_layers: 6
    dropout: 0.1
  task_classifier:
    hidden_dims: [512, 256]
    dropout: 0.2
  recommendation_model:
    hidden_dims: [512, 256, 128]
    dropout: 0.2
  reinforcement_learning:
    algorithm: ppo
    gamma: 0.99
    learning_rate: 0.0003

training:
  batch_size: 32
  learning_rate: 0.0001
  epochs: 50
  early_stopping:
    patience: 5
    min_delta: 0.001
  optimizer: adam
  scheduler:
    type: cosine_annealing
    t_max: 10

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
  threshold: 0.5

api:
  host: 0.0.0.0
  port: 8000
  debug: true

features:
  task_management: true
  reminders: true
  scheduling: true
  goal_tracking: true
  adaptive_recommendations: true
  continuous_learning: true